In [2]:
import numpy as np

In [ ]:
a=np.arange(22,71,2) #find out the even number 21 to 70
a

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54,
       56, 58, 60, 62, 64, 66, 68, 70])

In [ ]:
c=np.arange(21,72,2) #find out the odd numb 21 to 71
c

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53,
       55, 57, 59, 61, 63, 65, 67, 69, 71])

In [ ]:
s1=np.arange(1,37) #create a array 1 to 36
s1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [20]:
s2=s1.reshape(9,4) # 9 rows nd 4 columns
s2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32],
       [33, 34, 35, 36]])

In [ ]:
s2[1:4,2:5] #slicing the row nd

array([[ 7,  8],
       [11, 12],
       [15, 16]])

In [ ]:
s2[::2,::2] #slicing the row nd

array([[ 1,  3],
       [ 9, 11],
       [17, 19],
       [25, 27],
       [33, 35]])

In [ ]:
s2[::-1] #reverse the row order

array([[33, 34, 35, 36],
       [29, 30, 31, 32],
       [25, 26, 27, 28],
       [21, 22, 23, 24],
       [17, 18, 19, 20],
       [13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])